import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>トレードオフスライダー</header>
      <main>
        <div>
          {/* tableHeader */}
          <ul className="flex">
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
          </ul>

          {/* rows */}
          <ul>
            <li className="flex">
              <div>&lt;--◯--------------&gt;</div>
              <div>スコープ</div>
            </li>
          </ul>
        </div>
      </main>
    </div>
  )
}

export default Home
